### ISSUE TITLE
Duplicate code test/conditions-n-loops-tests.js

### ISSUE THREAD

**Issue by dimitra86** [rolling-scopes-school/core-js-conditions-n-loops-tasks#11]
it.optional(
    'canQueenCaptureKing should return true if a queen can capture a king',
    () => {
      assert.equal(
        tasks.canQueenCaptureKing({ x: 1, y: 1 }, { x: 5, y: 5 }),
        true
      );
      assert.equal(
        tasks.canQueenCaptureKing({ x: 2, y: 1 }, { x: 2, y: 8 }),
        true
      );
      assert.equal(
        tasks.canQueenCaptureKing({ x: 1, y: 1 }, { x: 2, y: 8 }),
        false
      );
      assert.equal(
        tasks.canQueenCaptureKing({ x: 1, y: 1 }, { x: 2, y: 8 }),!!!!!!!!!

**Comment by MikAleinik** [comment]
Thank you!
I have made corrections to this task.
