### ISSUE TITLE
Presence of Obfuscated and Minified JavaScript Files in Test Suite Poses Security Risk And Loss of User Data

### ISSUE THREAD

**Issue by vetalapo** [rolling-scopes-school/core-js-conditions-n-loops-tasks#19]
Dear RSSchool,

I hope this message finds you well. I am writing to bring your attention to a critical issue identified in the test suite of the [core-js-conditions-n-loops-tasks](https://github.com/rolling-scopes-school/core-js-conditions-n-loops-tasks) GitHub repository. The concern revolves around the presence of obfuscated and minified JavaScript files within the test suite, for which no corresponding source code is available.

Issue Description:
The current state of the test suite includes JavaScript files that have been obfuscated and minified, making it impossible to review and rebuild the code to confirm its content. This lack of transparency raises serious security concerns, as it introduces the risk of potential malicious code that could compromise the integrity of the repository and, consequently, the security of user data.

Potential Implications:
Security Risk: The obfuscated code may contain malicious elements that could compromise the security of the entire repository and, consequently, user data.

Inability to Verify Code: Without access to the source code, it is challenging to verify the legitimacy and security of the obfuscated and minified files.

Proposed Actions:
Review and Refactor Code: It is recommended to review and refactor the obfuscated and minified JavaScript files to ensure transparency and mitigate the risk of security threats.

Provide Source Code: If possible, please provide the corresponding source code for the obfuscated files, allowing for a thorough review and analysis.

Implement Code Analysis: Consider implementing code analysis tools to identify and address potential security vulnerabilities in the repository.

Timeline:
Given the severity of the potential security risk, it is recommended to address this issue promptly. A timeline for resolution would be greatly appreciated to ensure the continued security and integrity of the repository.

Your prompt attention to this matter is crucial, and I believe that addressing this issue swiftly will contribute to the overall security of the project, and trust of its users.

Thank you for your time and understanding.

**Comment by MikAleinik** [comment]
I realized the importance of the issue you were discussing in PR #18 
and changes are indeed necessary.
Thank you for your persistence - the suggested additions will definitely be made
And this is an important experience for me, thank you
@valerydluski for info
